Fix peerDependencies for rollup
Building with Vite ⚡️
failed to load config from /Users/hery/Devel/Propitech/bookshelf/vite.config.mts
error during build:
Error: rollup-plugin-gzip tried to access rollup (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: rollup (via "rollup/package.json")
Required by: rollup-plugin-gzip@virtual:225c6d7c7db38e4c3043ae94009eaea674e421fa7f71b6b31598a6bdc6fe21a03c985114a5029a9c5714fec060bc4ddc32cdf5a6e48ad158bff3fa65f9841f14#npm:3.1.1 (via /Users/hery/Devel/Propitech/bookshelf/.yarn/__virtual__/rollup-plugin-gzip-virtual-c4f8b2928d/4/.yarn/berry/cache/rollup-plugin-gzip-npm-3.1.1-a89e951fed-10c0.zip/node_modules/rollup-plugin-gzip/dist-es/index.mjs)

Ancestor breaking the chain: vite-plugin-rails@virtual:81107a6355f82af65b769cf7e77f139059e981555e9432359b9655b314f864b3141d441cc8f064f79d0476ba7abcc51e1fb622f63e0a0fc9d127c3aba7119d5a#npm:0.5.0